# Generated by Django 5.1.1 on 2024-09-27 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
